updated workflow for health check

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -25,7 +25,7 @@ jobs:
             - name: Verify the docker image runs
               run: |
                   docker run -d -p 6800:6800 --name mini-node-app-test mini-node-app:latest
-                  sleep 5
+                  sleep 2
                   
             
             - name: run health check
@@ -35,10 +35,12 @@ jobs:
                       echo "Health check passed!"
                       break
                     else
-                      echo "Health check failed, retrying..."
-                      sleep 5
+                      echo "Health check failed, retrying... ($i/3)"
+                      sleep 2
                     fi
                   done
+                  echo "Health check failed after 3 attempts."
+                  exit 1
 
             - name: stop and remove test container
               run: |
